POST_TYPE_IMAGE = 1;
POST_TYPE_VIDEO = 2;

POST_INTERACTION_LIKE = 1;
POST_INTERACTION_DISLIKE = -1;
module.exports = {
    POST_TYPE_IMAGE: this.POST_TYPE_IMAGE,
    POST_TYPE_VIDEO: POST_TYPE_VIDEO,
    POST_INTERACTION_LIKE: POST_INTERACTION_LIKE,
    POST_INTERACTION_DISLIKE: POST_INTERACTION_DISLIKE,

};